export const countries = [
  "Afeganistão",
  "África do Sul",
  " Albânia",
  "Alemanha",
  "Andorra",
  "Angola",
  " Antígua e Barbuda",
  "Arábia Saudita",
  "Argélia",
  "Argentina",
  "Armênia",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Barein",
  "Belarus",
  "Bélgica",
  "Belize",
  "Benin",
  "Bolívia",
  "Bósnia e Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunei",
  "Bulgária",
  "Burkina Faso",
  "Burundi",
  "Butão",
  "Cabo Verde",
  "Camarões",
  "Camboja",
  "Canadá",
  "Catar",
  "Cazaquistão",
  "Chade",
  "Chile",
  "China",
  "Chipre",
  "Colômbia",
  "Comores",
  "Congo",
  "Costa do Marfim",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Dinamarca",
  "Djibouti",
  "Dominica",
  "Egito",
  "El Salvador",
  "Emirados Árabes Unidos",
  "Equador",
  "Eritréia",
  "Eslováquia",
  "Eslovênia",
  "Espanha",
  "Estados Unidos da América",
  "Estônia",
  "Eswatini",
  "Etiópia",
  "Fiji",
  "Filipinas",
  "Finlândia",
  "França",
  "Gabão",
  "Gâmbia",
  "Gana",
  "Geórgia",
  "Granada",
  "Grécia",
  "Guatemala",
  "Guiana",
  "Guiné",
  "Guiné Equatorial",
  "Guiné-Bissau",
  "Haiti",
  "Holanda",
  "Honduras",
  "Hungria",
  "Iêmen",
  "Ilhas Salomão",
  "Índia",
  "Indonésia",
  "Irã",
  "Iraque",
  "Irlanda",
  "Islândia",
  "Israel",
  "Itália",
  "Jamaica",
  "Japão",
  "Jordânia",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letônia",
  "Líbano",
  "Libéria",
  "Líbia",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Macedônia do Norte",
  "Madagáscar",
  "Malásia",
  "Malauí",
  "Maldivas",
  "Mali",
  "Malta",
  "Marrocos",
  "Maurício",
  "Mauritânia",
  "México",
  "Mianmar",
  "Micronésia",
  "Moçambique",
  "Moldávia",
  "Mônaco",
  "Mongólia",
  "Montenegro",
  "Namíbia",
  "Nauru",
  "Nepal",
  "Nicarágua",
  "Níger",
  "Nigéria",
  "Noruega",
  "Nova Zelândia",
  "Omã",
  "Palau",
  "Panamá",
  "Papua Nova Guiné",
  "Paquistão",
  "Paraguai",
  "Peru",
  "Polônia",
  "Portugal",
  "Quênia",
  "Quirguistão",
  "Reino Unido",
  "República Centro Africana",
  "República da Coréia",
  "República Democrática do Congo",
  "República Dominicana",
  "República Popular Democrática da Coréia",
  "República Tcheca",
  "Romênia",
  "Ruanda",
  "Rússia (Federação Russa)",
  "Samoa",
  "San Marino",
  "Santa Lúcia",
  "São Cristóvão e Nevis",
  "São Tomé e Príncipe",
  "São Vicente e Granadinas",
  "Seichelles",
  "Senegal",
  "Serra Leoa",
  "Sérvia",
  "Singapura",
  "Síria",
  "Somália",
  "Sri Lanka",
  "Sudão",
  "Sudão do Sul",
  "Suécia",
  "Suíça",
  "Suriname",
  "Tadjiquistão",
  "Tailândia",
  "Tanzânia",
  "Timor Leste",
  "Togo",
  "Tonga",
  "Trinidad e Tobago",
  "Tunísia",
  "Turcomenistão",
  "Turquia",
  "Tuvalu",
  "Ucrânia",
  "Uganda",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Venezuela",
  "Vietnã",
  "Zâmbia",
  "Zimbábue",
];
